### PR TITLE
Detect glibc version and add -lrt if needed

### PR DESCRIPTION
**Pull request by matlo607**
I was using RedHat 6.4 (old but still supported) and got a linker error of this kind: [\[stackoverflow\] Another “undefined reference” error when linking boost libraries](https://stackoverflow.com/questions/13653361/another-undefined-reference-error-when-linking-boost-libraries)
I don't have the original one anymore at disposal. The library I was building depended on boost_chono. One of the missing symbol was `clock_gettime`.

The issue come from the version of glibc I was using : 2.12
```
# man clock_gettime
...
    Link with -lrt (only for glibc versions before 2.17).
...
```

I added a check on glibc version. What do you think about it ?

### CODE REVIEW

**Comment by lasote** [comment]
The idea of checking the glibc version is interesting and could be useful as a Conan tool. I didn't know about this kind of issues with additional libs to link with, so thanks for sharing it.
Unfortunately something is failing with the gblic detection, see the Travis error traces.

**Comment by matlo607** [comment]
subprocess changed its API in python 3.5, older versions cannot find `subprocess.run()`
It seems to be ok now.

**Comment by lasote** [comment]
We use `subprocess.check_output` in the conan codebase in several places. Why don't call it directly instead of the wrapper?

**Comment by SSE4** [comment]
@matlo607 I suppose, it might be safe just always to link with librt, WDYT?

**Comment by matlo607** [comment]
@SSE4 I think it would be ok, librt should always be present on the machine so no problem at runtime.

**Pull request merged**
