### PR TITLE
feat(conan-boost): add use_icu option

### PR DESCRIPTION
**Pull request by ledocc**
add option boost:use_icu to use ICU in boost.locale and boost.regex

ICU require C++11 to build so settings cppstd=11 or above is required

I also increase the number of job on travis because this option double the number of build possibility

I also add 2 patch to boost.regex and boost.locale to correctly detect icu libraries.

### CODE REVIEW

**Comment by SSE4** [comment]
please fix CI errors: `The specified 'cppstd=11' is not available for 'Visual Studio 14'. Possible values are ['14', '17']'`

**Comment by ledocc** [comment]
use_icu feature require this environment variable to travis/appveyor CI
```
CONAN_REMOTES = https://api.bintray.com/conan/bincrafters/public-conan@True@bincrafters
CONAN_BUILD_POLICY = missing
```

**Comment by SSE4** [comment]
@ledocc seems like ICU isn't yet in conan-center
is it urgent for you or you can wait until we add it into conan-center?
I am going to submit inclusion request

**Comment by ledocc** [comment]
@SSE4 I can wait, thank you.
just tell me when its done, then I will fix conflicts.

**Comment by ledocc** [comment]
Hi,

I send a mail to bincrafters team on bintray to add them icu package into conan/conan-center, but no answer for now. Any news from your inclusion request ?

**Comment by SSE4** [comment]
@ledocc I am in process of updating ICU right now, will take a couple of days

**Comment by SSE4** [comment]
finally, ICU is in conan-center, so I am revisiting this one

**Comment by ledocc** [comment]
Nice news

Merge main branch in feature branch is not a good practice so I rebase my patch on release/1.70.0
I also remove feature.compile.cppstd test when use icu, 
this check should be done in icu package, not in boost package

**Comment by SSE4** [comment]
okay, go ahead :)

**Comment by SSE4** [comment]
@ledocc `TestUseICU` fails on appveyor, may you take a look?

**Comment by ledocc** [comment]
@SSE4 I'm fighting boost.build. I'm near to win. last round tomorrow.

**Comment by ledocc** [comment]
@SSE4 : 
AppVeyor failed because : 
- on msvc 2019
```
[00:14:44] bzip2/1.0.6@conan/stable: ERROR: Error downloading binary package: 'bzip2/1.0.6@conan/stable:8334c588c229b05feb8ace75d0841c244f0e0e92'
[00:14:44] Traceback (most recent call last):
[00:14:44]   ...
[00:14:44] conans.errors.ConanConnectionError: ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))
[00:14:44] 
[00:14:44] Unable to connect to upload_repo=https://api.bintray.com/conan/conan-community/conan
```


Travis failed because : 

- on clang  :
```
- icu/64.2@bincrafters/stable: WARN: Can't find a 'icu/64.2@bincrafters/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=clang, compiler.libcxx=libstdc++11, compiler.version=7.0, os=Linux
- Options: data_packaging=archive, fPIC=True, shared=False, silent=True, with_unit_tests=False
```
on Apple Clang:
```
- bzip2/1.0.6@conan/stable: WARN: Can't find a 'bzip2/1.0.6@conan/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=apple-clang, compiler.cppstd=11, compiler.version=9.0, os=Macos
- Options: build_executable=True, fPIC=True, shared=False
```

I will provide a patch for icu and bzip2 package. Keep in touch.

**Comment by SSE4** [comment]
@ledocc now it got much further: https://travis-ci.org/conan-community/conan-boost/builds/573745726 https://ci.appveyor.com/project/ConanCIintegration/conan-boost/builds/26792388
there are some undefined references
would be nice if you could address em

**Comment by ledocc** [comment]
all build pass now, thanks for https://github.com/bincrafters/conan-icu/pull/27/commits/9a6c593416a53a9ba22d2665ae1878bf0779b38a

**Comment by ledocc** [comment]
@SSE4: up

**Comment by SSE4** [comment]
@ledocc I am merging, as it has passed CI

**Pull request merged**
