### PR TITLE
1.66.0: Added Clang 3.9/4.0/5.0 to travis build matrix

### PR DESCRIPTION
**Pull request by helmesjo**

### CODE REVIEW

**Comment by helmesjo** [comment]
@lasote 
"Page" 1 & 2 (of 10) fails for each compiler version. Any hint to why? Does it need to be split up even more? (because that is what `CONAN_CURRENT_PAGE` does, right? Distributes the build to avoid the time-cap..?)

**Comment by lasote** [comment]
Yes, as it is distributed by math modules, the page 1 and 2 probably have 1 build more than the rest. Looking at the pages, there is a build per page, so probably we need 2 more pages for the failing configurations.

**Comment by helmesjo** [comment]
[#364.12 failed](https://travis-ci.org/conan-community/conan-boost/jobs/404338603), `Read timed out`:

```
conans.errors.ConanException: Error downloading file https://api.bintray.com/conan/conan-community/conan/v1/files/conan/zlib/1.2.11/stable/package/51b97b2bf2a6de96c720996769ff2a4039b820c7/conanmanifest.txt: 'HTTPSConnectionPool(host='api.bintray.com', port=443): Read timed out. (read timeout=60.0)'. [Remote: upload_repo]
```

**Comment by helmesjo** [comment]
All green @lasote

**Pull request merged**
