### PR TITLE
Boost: add support for unit tests and bcp

### PR DESCRIPTION
**Pull request by matlo607**
My company uses a "privatized" version of Boost. They hide Boost's symbols in a given namespace.
After the privatization, they want to check that Boost passes through the process smoothly and want to run the unit tests.
Within the scope of my work, I would need these features available natively in Boost's recipe so that I don't have to maintain patches.
My PR adds support for :
* [BCP (official tool to privatize boost)](http://www.boost.org/doc/libs/1_66_0/tools/bcp/doc/html/index.html)
* unit tests

You can play with the new parameters :
- `tests`
- `privatize`
- `privatization_namespace`
- `privatization_namespace_alias`
- `privatization_namespace_name`

on a small set of libraries with the script below.
```bash
#!/usr/bin/env bash

conan create . bcp/testing \
    -o boost:tests=True \
    -o boost:privatize=True \
    -o boost:privatization_namespace=False \
    -o boost:privatization_namespace_alias=True \
    -o boost:without_accumulators=True \
    -o boost:without_algorithm=True \
    -o boost:without_align=True \
    -o boost:without_any=True \
    -o boost:without_array=True \
    -o boost:without_asio=True \
    -o boost:without_assert=True \
    -o boost:without_assign=False \
    -o boost:without_atomic=True \
    -o boost:without_beast=True \
    -o boost:without_bimap=True \
    -o boost:without_bind=True \
    -o boost:without_callable_traits=True \
    -o boost:without_chrono=True \
    -o boost:without_circular_buffer=True \
    -o boost:without_compatibility=True \
    -o boost:without_compute=True \
    -o boost:without_concept_check=True \
    -o boost:without_config=True \
    -o boost:without_container=True \
    -o boost:without_context=True \
    -o boost:without_conversion=True \
    -o boost:without_convert=True \
    -o boost:without_core=True \
    -o boost:without_coroutine=True \
    -o boost:without_coroutine2=True \
    -o boost:without_crc=True \
    -o boost:without_date_time=True \
    -o boost:without_detail=True \
    -o boost:without_disjoint_sets=True \
    -o boost:without_dll=True \
    -o boost:without_dynamic_bitset=True \
    -o boost:without_endian=True \
    -o boost:without_exception=True \
    -o boost:without_fiber=True \
    -o boost:without_filesystem=True \
    -o boost:without_flyweight=True \
    -o boost:without_foreach=True \
    -o boost:without_format=True \
    -o boost:without_function=True \
    -o boost:without_function_types=True \
    -o boost:without_functional=True \
    -o boost:without_fusion=True \
    -o boost:without_geometry=True \
    -o boost:without_gil=True \
    -o boost:without_graph=True \
    -o boost:without_graph_parallel=True \
    -o boost:without_hana=True \
    -o boost:without_heap=True \
    -o boost:without_icl=True \
    -o boost:without_integer=True \
    -o boost:without_interprocess=True \
    -o boost:without_intrusive=True \
    -o boost:without_io=True \
    -o boost:without_iostreams=True \
    -o boost:without_iterator=True \
    -o boost:without_lambda=False \
    -o boost:without_lexical_cast=True \
    -o boost:without_libraries.htm=True \
    -o boost:without_local_function=True \
    -o boost:without_locale=True \
    -o boost:without_lockfree=True \
    -o boost:without_log=True \
    -o boost:without_logic=True \
    -o boost:without_math=True \
    -o boost:without_metaparse=True \
    -o boost:without_move=True \
    -o boost:without_mp11=True \
    -o boost:without_mpi=True \
    -o boost:without_mpl=True \
    -o boost:without_msm=True \
    -o boost:without_multi_array=True \
    -o boost:without_multi_index=True \
    -o boost:without_multiprecision=True \
    -o boost:without_numeric=True \
    -o boost:without_optional=True \
    -o boost:without_parameter=True \
    -o boost:without_phoenix=True \
    -o boost:without_poly_collection=True \
    -o boost:without_polygon=True \
    -o boost:without_pool=True \
    -o boost:without_predef=True \
    -o boost:without_preprocessor=True \
    -o boost:without_process=True \
    -o boost:without_program_options=True \
    -o boost:without_property_map=True \
    -o boost:without_property_tree=True \
    -o boost:without_proto=True \
    -o boost:without_ptr_container=True \
    -o boost:without_python=True \
    -o boost:without_qvm=True \
    -o boost:without_random=True \
    -o boost:without_range=True \
    -o boost:without_ratio=True \
    -o boost:without_rational=True \
    -o boost:without_regex=False \
    -o boost:without_scope_exit=True \
    -o boost:without_serialization=True \
    -o boost:without_signals=True \
    -o boost:without_signals2=True \
    -o boost:without_smart_ptr=True \
    -o boost:without_sort=True \
    -o boost:without_spirit=True \
    -o boost:without_stacktrace=True \
    -o boost:without_statechart=True \
    -o boost:without_static_assert=True \
    -o boost:without_system=True \
    -o boost:without_test=False \
    -o boost:without_thread=True \
    -o boost:without_throw_exception=True \
    -o boost:without_timer=True \
    -o boost:without_tokenizer=True \
    -o boost:without_tti=True \
    -o boost:without_tuple=True \
    -o boost:without_type_erasure=True \
    -o boost:without_type_index=True \
    -o boost:without_type_traits=True \
    -o boost:without_typeof=True \
    -o boost:without_units=True \
    -o boost:without_unordered=True \
    -o boost:without_utility=True \
    -o boost:without_uuid=True \
    -o boost:without_variant=True \
    -o boost:without_vmd=True \
    -o boost:without_wave=True \
    -o boost:without_winapi=True \
    -o boost:without_xpressive=True
```

Please could I have your feedback about this first draft ?

### CODE REVIEW

**Comment by lasote** [comment]
Wow, there is a lot of new code. Honestly, I don't have time enough to validate it (and understand it) properly until there is a higher support from the community to introduce this feature.
The Boost recipe is complex enough and probably more than enough for most people, I would recommend you to fork the repository and add all that logic to your fork.
If things change and people really request this feature we can reconsider it.

**Comment by matlo607** [comment]
I share your opinion that there are a lot of changes in this PR, that's why I talked about "a first draft".
I propose to split this PR in several ones so that it will be easier to validate.
I would be very happy to see these patches upstream.

Do you know if someone is/was working on a builder for bjam (alike `conans.client.build.cmake` or `conans.client.build.autotools_environment`) ?
It could simplify a lot the recipe.

Moreover I had to parse the logs myself to get a clear feedback of what's going on. bjam's output is not humanly readable.
I discovered https://github.com/arvidn/conan-boost-build-gen created by @arvidn that has been integrated into conan (https://github.com/conan-io/conan/pull/1800). Do you know if there is ongoing projects to create a log parser for bjam ?

**Comment by lasote** [comment]
Probably the bincrafters community have some build helper and some other tool for managing bjam. 
You can join the slack cpplang.slack.com and the #bincrafters channel and ask there.

**Comment by SSE4** [comment]
hi @matlo607 
I am closing this outdated PR, and I've opened new issue to track bcp feature https://github.com/conan-community/community/issues/141
I'll add required changes soon and let you know

**Pull request closed without merging**
