### PR TITLE
Fix cross compiling bug when CXX has multiple values

### PR DESCRIPTION
**Pull request by GeorgeScrivener**
Some cross compiler toolchains set CC, CXX & LD with multiple arguments,
which causes the build to fail.
As a workaround for this, modify the environment before building by
moving any extra arguments in to the corresponding flag

### CODE REVIEW

**Comment by lasote** [comment]
I would like to understand where is the real issue, as a workaround it looks pretty big.
@grafikrobot any feedback here?

**Comment by GeorgeScrivener** [comment]
This is the error I was getting:
```
### Using 'gcc' toolset.
###
rm -rf bootstrap
mkdir bootstrap
gcc -o bootstrap/jam0 command.c compile.c constants.c debug.c execcmd.c frames.c function.c glob.c hash.c hdrmacro.c headers.c jam.c jambase.c jamgram.c lists.c make.c make1.c object.c option.c output.c parse.c pathsys.c regexp.c rules.c scan.c search.c subst.c timestamp.c variable.c modules.c strings.c filesys.c builtins.c class.c cwd.c native.c md5.c w32_getreg.c modules/set.c modules/path.c modules/regex.c modules/property-set.c modules/sequence.c modules/order.c execunix.c fileunix.c pathunix.c
./bootstrap/jam0 -f build.jam --toolset=gcc --toolset-root= clean
build.jam:192: in module scope
*** argument error
* rule toolset ( name command .type ? : opt.out + : opt.define * : flags * : linklibs * )
* called with: ( cc arm-poky-linux-gnueabi-gcc -march=armv7ve -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a15 --sysroot=/opt/hd271dist/2.0.0/sysroots/cortexa15hf-neon-poky-linux-gnueabi : -o  : -D : -O2 -pipe -g -feliminate-unused-debug-types -s -O :  )
* extra argument -mfpu=neon
build.jam:156:see definition of rule 'toolset' being called
```


`CXX` was set to `arm-poky-linux-gnueabi-g++  -march=armv7ve -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a15 --sysroot=/opt/hd271dist/2.0.0/sysroots/cortexa15hf-neon-poky-linux-gnueabi`

**Comment by liberforce** [comment]
I guess the bug would affect people using a compiler cache like `ccache` to build, so that looks like a valid use case.

**Comment by SSE4** [comment]
@GeorgeScrivener could you check your PR according to @grafikrobot suggestion? I think just add quotation to CC/CXX is cleaner approach, instead of splitting CC into CC and CFLAGS (which is actually, doesn't always have same effect)

**Comment by SSE4** [comment]
@grafikrobot actually, I was trying quoting multiple arguments on MacOS, and it didn't work well for me. I'll paste log and my user config.

**Comment by SSE4** [comment]
I am closing this.
should be fixed by: https://github.com/conan-community/conan-boost/commit/e9c346cc7ab95913951f0e613478a295c68cb0f1

**Pull request closed without merging**
