### PR TITLE
added serval Boost 1.70.0 patches

### PR DESCRIPTION
**Pull request by Johnnyxy**
Added a patch that is provided officially by Boost (see https://www.boost.org/users/history/version_1_70_0.html).

### CODE REVIEW

**Comment by SSE4** [comment]
awesome! thanks a lot for your contribution

**Comment by Johnnyxy** [comment]
@SSE4 
As you already saw another big issue with the QNX SDP 7.0 compiler here: https://github.com/boostorg/config/issues/288
I have fixed that for Boost 1.70.0 recipe too (still only locally) by providing the appropriate header for the compiler at preprocessing-time as ```export_sources``` entry in the recipe.

Would this be ok too to provide this into the pull-request too?

**Comment by SSE4** [comment]
@Johnnyxy sure

**Comment by Johnnyxy** [comment]
@SSE4 
Following the discussion here: https://github.com/conan-io/conan/issues/5359

I tried to integrate QNX support into the Boost recipe. But as QNX specifically has targets for e.g. ```aarch64le``` and ```armv7le``` and not only ```armv8``` or ```armv7``` this is still an unsatisfying situation. Locally I have added the architectures to my ```settings.yml``` to solve this without doubt for what I build for.

At the moment I cannot put this into the pull-request with the available Conan architectures as this would be too unspecific in my opinion. I will open up another discussion for QNX support.

**Comment by SSE4** [comment]
@Johnnyxy should I wait or it's ready to be merged now?

**Comment by Johnnyxy** [comment]
@SSE4 
It depends.
The current state of the PR is that it includes the official patch for Boost.Beast and it is preparing for QNX support in general.

But as the recipe itself does not support calling QNX at the moment because of the target-mismatching (armv7->armv7le, ...) what we maybe should discuss separately, it would be more a matter of opinion to include the PR or not.

I would say we can include it as it does not affect the non-QNX users. And other QNX users could review the changes and give feedback.

**Comment by SSE4** [comment]
@Johnnyxy okay, let's merge this one then, and do separated PR for QNX

**Pull request merged**
